<!DOCTYPE html>
<html>
<head>
  <title>Terms and Conditions</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }

    h1 {
      text-align: center;
      margin-bottom: 20px;
    }

    h2 {
      margin-bottom: 10px;
    }

    p {
      margin-bottom: 10px;
    }

    ol {
      padding-left: 30px;
      margin-bottom: 20px;
    }

    li {
      margin-bottom: 5px;
    }

    footer {
      margin-top: 50px;
      text-align: center;
    }
  </style>
</head>
<body>
  <!-- <h1>Terms and Conditions</h1> -->
  <h1>Welcome to the GTRON MLM Program, operated by GTRON Corporation . By participating in this Program, you agree to the following terms and conditions. Please read them carefully before joining in the program.<h1>

<p>1. Program Overview:

The GTRON MLM Program is a multi-level marketing initiative that allows Participants to earn commissions by promoting and selling GTRON products and services. Participants can recruit new members into their downline and earn bonuses based on the sales performance of their downline members.
</p>

<p>2. Eligibility:

To participate in the GTRON MLM Program, you must be of legal age in your jurisdiction and abide by these terms and conditions. You are responsible for ensuring the accuracy and completeness of the information you provide during registration.
</p>

<p>3. Enrollment:

To enroll in the Program, you must complete the online registration process on the official GTRON website. Upon successful registration, you will be provided with a unique Participant ID and a back-office dashboard for managing your business activities.
  </p>

<p>4.Compensation Plan:

GTRON operates on a multi-level compensation plan, allowing you to earn commissions based on your personal sales and the sales generated by your downline members. The compensation plan structure, commission rates, and qualification criteria will be outlined in the official GTRON compensation plan document, which you will have access to upon enrollment.
  </p>

<p>5.Confidentiality:

During your participation in the Program, you may gain access to confidential information about GTRON's business operations, products, and strategies. You agree to keep such information confidential and not disclose it to any third parties.
  </p>

 <p>6.Changes to Terms:

GTRON reserves the right to modify these terms and conditions at any time. Participants will be notified of any changes, and continued participation implies acceptance of the updated terms.

  </p>

  <p>
By enrolling in the GTRON MLM Program, you acknowledge that you have read, understood, and agree to abide by these terms and conditions. If you do not agree with these terms, please do not enroll in the Program.
  </p>

  <p>
For questions or concerns, please contact us.
  </p>
<p>
By enrolling, you acknowledge that you have read and agree to these terms and conditions.
  </p>
  
  <!-- <h2>First Bonus</h2>
  <p>
    - Those who complete a minimum of 5 members in the first level and 25 members in the second level will get 100 USDT.<br>
    - Those who complete a minimum of 125 members in the third level will get an additional 200 USDT.
  </p>

  <h2>Second Bonus</h2>
  <p>
    - Those who complete a minimum of 10 members in the first level and 100 members in the second level will get 200 USDT.<br>
    - Those who complete a minimum of 1000 members in the third level will get an additional 2750 USDT.
  </p>
  
  <p>M GtronTM</p>

  <footer>
    &copy; [M GtronTM] - All rights reserved.
  </footer> -->
</body>
</html>
